namespace Essentials.Extensions
{
    internal enum KeywordType
    {
        PLAYER,
        DISPLAYNAME,
        USERNAME,
        BALANCE,
        MAILS,
        WORLD,
        WORLDNAME,
        ONLINE,
        UNIQUE,
        WORLDS,
        PLAYERLIST,
        TIME,
        DATE,
        WORLDTIME12,
        WORLDTIME24,
        WORLDDATE,
        COORDS,
        TPS,
        UPTIME,
        IP,
        ADDRESS,
        PLUGINS,
        VERSION
    }
}